# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Stockage\GIT\GitHub\smartest2\ui\ui_attribute_lineedit_str.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AttributeLineeditStr(object):
    def setupUi(self, AttributeLineeditStr):
        AttributeLineeditStr.setObjectName("AttributeLineeditStr")
        AttributeLineeditStr.resize(750, 40)
        AttributeLineeditStr.setMinimumSize(QtCore.QSize(575, 40))
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(AttributeLineeditStr)
        self.horizontalLayout_3.setContentsMargins(15, 7, 15, 7)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.num_attrib = QtWidgets.QLabel(AttributeLineeditStr)
        self.num_attrib.setMinimumSize(QtCore.QSize(50, 26))
        self.num_attrib.setMaximumSize(QtCore.QSize(50, 26))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.num_attrib.setFont(font)
        self.num_attrib.setAlignment(QtCore.Qt.AlignCenter)
        self.num_attrib.setObjectName("num_attrib")
        self.horizontalLayout_3.addWidget(self.num_attrib)
        self.name_attrib = QtWidgets.QLabel(AttributeLineeditStr)
        self.name_attrib.setMinimumSize(QtCore.QSize(240, 26))
        self.name_attrib.setMaximumSize(QtCore.QSize(240, 26))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.name_attrib.setFont(font)
        self.name_attrib.setObjectName("name_attrib")
        self.horizontalLayout_3.addWidget(self.name_attrib)
        self.type_attrib = QtWidgets.QLabel(AttributeLineeditStr)
        self.type_attrib.setMinimumSize(QtCore.QSize(40, 26))
        self.type_attrib.setMaximumSize(QtCore.QSize(40, 26))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.type_attrib.setFont(font)
        self.type_attrib.setStyleSheet("QLabel{color: grey; }")
        self.type_attrib.setAlignment(QtCore.Qt.AlignCenter)
        self.type_attrib.setObjectName("type_attrib")
        self.horizontalLayout_3.addWidget(self.type_attrib)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.value_attrib = QtWidgets.QPlainTextEdit(AttributeLineeditStr)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.value_attrib.sizePolicy().hasHeightForWidth())
        self.value_attrib.setSizePolicy(sizePolicy)
        self.value_attrib.setMinimumSize(QtCore.QSize(100, 26))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.value_attrib.setFont(font)
        self.value_attrib.setAcceptDrops(False)
        self.value_attrib.setStyleSheet("QPlainTextEdit{padding-left: 5px; border: 1px solid #8f8f91; border-right-width: 0px; border-top-left-radius:5px; border-bottom-left-radius: 5px; background: #fff}")
        self.value_attrib.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.value_attrib.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.value_attrib.setTabChangesFocus(False)
        self.value_attrib.setBackgroundVisible(False)
        self.value_attrib.setObjectName("value_attrib")
        self.horizontalLayout.addWidget(self.value_attrib)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(AttributeLineeditStr)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("QLabel{border: 1px solid #8f8f91; border-left-width: 0px; border-top-width: 0px; border-bottom-right-radius: 5px; background-color:#FFFFFF; }")
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 2)
        self.formatting_bt = QtWidgets.QPushButton(AttributeLineeditStr)
        self.formatting_bt.setMinimumSize(QtCore.QSize(40, 26))
        self.formatting_bt.setMaximumSize(QtCore.QSize(40, 26))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.formatting_bt.setFont(font)
        self.formatting_bt.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-left-width: 0px; padding-left: 1px; border-bottom-width: 0px; padding-bottom: 1px; border-top-right-radius: 5px ; background-color:#FFFFFF; }\n"
"QPushButton:hover{border-left-width: 1px; border-bottom-width: 1px; padding: 0px; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC); }\n"
"QPushButton:pressed{border-left-width: 1px; border-bottom-width: 1px; padding: 0px; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8); }")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Images/format.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.formatting_bt.setIcon(icon)
        self.formatting_bt.setIconSize(QtCore.QSize(16, 16))
        self.formatting_bt.setFlat(True)
        self.formatting_bt.setObjectName("formatting_bt")
        self.gridLayout.addWidget(self.formatting_bt, 0, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)

        self.retranslateUi(AttributeLineeditStr)
        QtCore.QMetaObject.connectSlotsByName(AttributeLineeditStr)

    def retranslateUi(self, AttributeLineeditStr):
        pass
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AttributeLineeditStr = QtWidgets.QWidget()
    ui = Ui_AttributeLineeditStr()
    ui.setupUi(AttributeLineeditStr)
    AttributeLineeditStr.show()
    sys.exit(app.exec_())
