# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Stockage\GIT\GitHub\smartest2\ui\ui_attribute_date.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AttributeDate(object):
    def setupUi(self, AttributeDate):
        AttributeDate.setObjectName("AttributeDate")
        AttributeDate.resize(750, 40)
        AttributeDate.setMinimumSize(QtCore.QSize(575, 40))
        AttributeDate.setMaximumSize(QtCore.QSize(16777215, 40))
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(AttributeDate)
        self.horizontalLayout_3.setContentsMargins(15, 2, 15, 2)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.num_attrib = QtWidgets.QLabel(AttributeDate)
        self.num_attrib.setMinimumSize(QtCore.QSize(50, 26))
        self.num_attrib.setMaximumSize(QtCore.QSize(50, 26))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.num_attrib.setFont(font)
        self.num_attrib.setAlignment(QtCore.Qt.AlignCenter)
        self.num_attrib.setObjectName("num_attrib")
        self.horizontalLayout_3.addWidget(self.num_attrib)
        self.name_attrib = QtWidgets.QLabel(AttributeDate)
        self.name_attrib.setMinimumSize(QtCore.QSize(240, 26))
        self.name_attrib.setMaximumSize(QtCore.QSize(240, 26))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.name_attrib.setFont(font)
        self.name_attrib.setText("")
        self.name_attrib.setObjectName("name_attrib")
        self.horizontalLayout_3.addWidget(self.name_attrib)
        self.type_attrib = QtWidgets.QLabel(AttributeDate)
        self.type_attrib.setMinimumSize(QtCore.QSize(40, 26))
        self.type_attrib.setMaximumSize(QtCore.QSize(40, 26))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.type_attrib.setFont(font)
        self.type_attrib.setStyleSheet("QLabel{color: grey; }")
        self.type_attrib.setText("ABC")
        self.type_attrib.setAlignment(QtCore.Qt.AlignCenter)
        self.type_attrib.setObjectName("type_attrib")
        self.horizontalLayout_3.addWidget(self.type_attrib)
        self.date_layer = QtWidgets.QHBoxLayout()
        self.date_layer.setSpacing(0)
        self.date_layer.setObjectName("date_layer")
        self.value_attrib = QtWidgets.QLineEdit(AttributeDate)
        self.value_attrib.setMinimumSize(QtCore.QSize(100, 26))
        self.value_attrib.setMaximumSize(QtCore.QSize(16777215, 26))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.value_attrib.setFont(font)
        self.value_attrib.setStyleSheet("QLineEdit{padding-left: 5px; border: 1px solid #8f8f91; border-right-width: 0px; border-top-left-radius:5px; border-bottom-left-radius: 5px; }")
        self.value_attrib.setObjectName("value_attrib")
        self.date_layer.addWidget(self.value_attrib)
        self.calendar_bt = QtWidgets.QPushButton(AttributeDate)
        self.calendar_bt.setMinimumSize(QtCore.QSize(40, 26))
        self.calendar_bt.setMaximumSize(QtCore.QSize(40, 26))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.calendar_bt.setFont(font)
        self.calendar_bt.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-left-width: 0px; padding-left: 1px;  border-top-right-radius: 5px ; border-bottom-right-radius: 5px; background-color:#FFFFFF; }\n"
"QPushButton:hover{border-left-width: 1px; padding: 0px; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC); }\n"
"QPushButton:pressed{border-left-width: 1px; padding: 0px; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8); }")
        self.calendar_bt.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Images/calendar.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.calendar_bt.setIcon(icon)
        self.calendar_bt.setIconSize(QtCore.QSize(16, 16))
        self.calendar_bt.setFlat(True)
        self.calendar_bt.setObjectName("calendar_bt")
        self.date_layer.addWidget(self.calendar_bt)
        self.horizontalLayout_3.addLayout(self.date_layer)

        self.retranslateUi(AttributeDate)
        QtCore.QMetaObject.connectSlotsByName(AttributeDate)

    def retranslateUi(self, AttributeDate):
        _translate = QtCore.QCoreApplication.translate
        self.type_attrib.setToolTip(_translate("AttributeDate", "Texte"))
        self.calendar_bt.setToolTip(_translate("AttributeDate", "Ouvrir le calendrier"))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AttributeDate = QtWidgets.QWidget()
    ui = Ui_AttributeDate()
    ui.setupUi(AttributeDate)
    AttributeDate.show()
    sys.exit(app.exec_())
