# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Stockage\GIT\GitHub\smartest2\ui\ui_attribute_lineedit.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AttributeLineedit(object):
    def setupUi(self, AttributeLineedit):
        AttributeLineedit.setObjectName("AttributeLineedit")
        AttributeLineedit.resize(750, 40)
        AttributeLineedit.setMinimumSize(QtCore.QSize(575, 40))
        AttributeLineedit.setMaximumSize(QtCore.QSize(16777215, 40))
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(AttributeLineedit)
        self.horizontalLayout_3.setContentsMargins(15, 2, 15, 2)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.num_attrib = QtWidgets.QLabel(AttributeLineedit)
        self.num_attrib.setMinimumSize(QtCore.QSize(50, 26))
        self.num_attrib.setMaximumSize(QtCore.QSize(50, 26))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.num_attrib.setFont(font)
        self.num_attrib.setAlignment(QtCore.Qt.AlignCenter)
        self.num_attrib.setObjectName("num_attrib")
        self.horizontalLayout_3.addWidget(self.num_attrib)
        self.name_attrib = QtWidgets.QLabel(AttributeLineedit)
        self.name_attrib.setMinimumSize(QtCore.QSize(240, 26))
        self.name_attrib.setMaximumSize(QtCore.QSize(240, 26))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.name_attrib.setFont(font)
        self.name_attrib.setObjectName("name_attrib")
        self.horizontalLayout_3.addWidget(self.name_attrib)
        self.type_attrib = QtWidgets.QLabel(AttributeLineedit)
        self.type_attrib.setMinimumSize(QtCore.QSize(40, 26))
        self.type_attrib.setMaximumSize(QtCore.QSize(40, 26))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.type_attrib.setFont(font)
        self.type_attrib.setStyleSheet("QLabel{color: grey; }")
        self.type_attrib.setAlignment(QtCore.Qt.AlignCenter)
        self.type_attrib.setObjectName("type_attrib")
        self.horizontalLayout_3.addWidget(self.type_attrib)
        self.lineedit_layer = QtWidgets.QHBoxLayout()
        self.lineedit_layer.setSpacing(0)
        self.lineedit_layer.setObjectName("lineedit_layer")
        self.value_attrib = QtWidgets.QLineEdit(AttributeLineedit)
        self.value_attrib.setMinimumSize(QtCore.QSize(100, 26))
        self.value_attrib.setMaximumSize(QtCore.QSize(16777215, 26))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.value_attrib.setFont(font)
        self.value_attrib.setStyleSheet("QLineEdit{padding-left: 5px; border: 1px solid #8f8f91; border-right-width: 0px; border-top-left-radius:5px; border-bottom-left-radius: 5px; }")
        self.value_attrib.setText("")
        self.value_attrib.setObjectName("value_attrib")
        self.lineedit_layer.addWidget(self.value_attrib)
        self.unit_attrib = QtWidgets.QLabel(AttributeLineedit)
        self.unit_attrib.setMinimumSize(QtCore.QSize(80, 26))
        self.unit_attrib.setMaximumSize(QtCore.QSize(80, 26))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.unit_attrib.setFont(font)
        self.unit_attrib.setStyleSheet("QLabel{border: 1px solid #8f8f91; border-left-width: 0px; padding-left: 1px; padding-right: 10px; border-top-right-radius: 5px; border-bottom-right-radius: 5px; color: grey;  background-color:#FFFFFF; }")
        self.unit_attrib.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.unit_attrib.setObjectName("unit_attrib")
        self.lineedit_layer.addWidget(self.unit_attrib)
        self.horizontalLayout_3.addLayout(self.lineedit_layer)

        self.retranslateUi(AttributeLineedit)
        QtCore.QMetaObject.connectSlotsByName(AttributeLineedit)

    def retranslateUi(self, AttributeLineedit):
        _translate = QtCore.QCoreApplication.translate
        self.unit_attrib.setToolTip(_translate("AttributeLineedit", "Unité"))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AttributeLineedit = QtWidgets.QWidget()
    ui = Ui_AttributeLineedit()
    ui.setupUi(AttributeLineedit)
    AttributeLineedit.show()
    sys.exit(app.exec_())
