# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Stockage\GIT\GitHub\smartest2\ui\ui_attribute_233.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Attribute233(object):
    def setupUi(self, Attribute233):
        Attribute233.setObjectName("Attribute233")
        Attribute233.resize(381, 455)
        self.bt_sh = QtWidgets.QPushButton(Attribute233)
        self.bt_sh.setGeometry(QtCore.QRect(19, 16, 75, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.bt_sh.setFont(font)
        self.bt_sh.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-radius:5px ; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #FFFFFF, stop:1 #BAD0E7); }\n"
"QPushButton:checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8); }\n"
"QPushButton:hover:!checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC); }\n"
"QPushButton:hover::checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #BAD0E7, stop:1 #FFFFFF); }")
        self.bt_sh.setCheckable(True)
        self.bt_sh.setObjectName("bt_sh")
        self.buttonGroup = QtWidgets.QButtonGroup(Attribute233)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.bt_sh)
        self.bt_sa = QtWidgets.QPushButton(Attribute233)
        self.bt_sa.setGeometry(QtCore.QRect(19, 114, 75, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.bt_sa.setFont(font)
        self.bt_sa.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-radius:5px ; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #FFFFFF, stop:1 #BAD0E7); }\n"
"QPushButton:checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8); }\n"
"QPushButton:hover:!checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC); }\n"
"QPushButton:hover::checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #BAD0E7, stop:1 #FFFFFF); }")
        self.bt_sa.setCheckable(True)
        self.bt_sa.setObjectName("bt_sa")
        self.buttonGroup.addButton(self.bt_sa)
        self.bt_se = QtWidgets.QPushButton(Attribute233)
        self.bt_se.setGeometry(QtCore.QRect(19, 213, 75, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.bt_se.setFont(font)
        self.bt_se.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-radius:5px ; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #FFFFFF, stop:1 #BAD0E7); }\n"
"QPushButton:checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8); }\n"
"QPushButton:hover:!checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC); }\n"
"QPushButton:hover::checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #BAD0E7, stop:1 #FFFFFF); }")
        self.bt_se.setCheckable(True)
        self.bt_se.setObjectName("bt_se")
        self.buttonGroup.addButton(self.bt_se)
        self.bt_nh = QtWidgets.QPushButton(Attribute233)
        self.bt_nh.setGeometry(QtCore.QRect(19, 311, 75, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.bt_nh.setFont(font)
        self.bt_nh.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-radius:5px ; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #FFFFFF, stop:1 #BAD0E7); }\n"
"QPushButton:checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8); }\n"
"QPushButton:hover:!checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC); }\n"
"QPushButton:hover::checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #BAD0E7, stop:1 #FFFFFF); }")
        self.bt_nh.setCheckable(True)
        self.bt_nh.setObjectName("bt_nh")
        self.buttonGroup.addButton(self.bt_nh)
        self.fond = QtWidgets.QWidget(Attribute233)
        self.fond.setGeometry(QtCore.QRect(0, 417, 381, 38))
        self.fond.setMinimumSize(QtCore.QSize(0, 24))
        self.fond.setStyleSheet("QWidget#fond{background: #DBE4EE}")
        self.fond.setObjectName("fond")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.fond)
        self.horizontalLayout_3.setContentsMargins(0, 0, 9, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.bt_valider = QtWidgets.QPushButton(self.fond)
        self.bt_valider.setMinimumSize(QtCore.QSize(120, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.bt_valider.setFont(font)
        self.bt_valider.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-radius: 5px ; padding-right: 10px; padding-left: 10px; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #FFFFFF, stop:1 #BAD0E7); }\n"
"QPushButton:hover{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC); }\n"
"QPushButton:pressed{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8); }")
        self.bt_valider.setIconSize(QtCore.QSize(18, 18))
        self.bt_valider.setShortcut("Ctrl+S")
        self.bt_valider.setObjectName("bt_valider")
        self.horizontalLayout_3.addWidget(self.bt_valider)
        self.bt_quitter = QtWidgets.QPushButton(self.fond)
        self.bt_quitter.setMinimumSize(QtCore.QSize(120, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.bt_quitter.setFont(font)
        self.bt_quitter.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-radius: 5px ; padding-right: 10px; padding-left: 10px; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #FFFFFF, stop:1 #BAD0E7); }\n"
"QPushButton:hover{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC); }\n"
"QPushButton:pressed{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8); }")
        self.bt_quitter.setIconSize(QtCore.QSize(18, 18))
        self.bt_quitter.setShortcut("Esc")
        self.bt_quitter.setObjectName("bt_quitter")
        self.horizontalLayout_3.addWidget(self.bt_quitter)

        self.retranslateUi(Attribute233)
        QtCore.QMetaObject.connectSlotsByName(Attribute233)

    def retranslateUi(self, Attribute233):
        _translate = QtCore.QCoreApplication.translate
        self.bt_valider.setText(_translate("Attribute233", " Valider"))
        self.bt_quitter.setText(_translate("Attribute233", " Annuler"))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Attribute233 = QtWidgets.QWidget()
    ui = Ui_Attribute233()
    ui.setupUi(Attribute233)
    Attribute233.show()
    sys.exit(app.exec_())
