# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Stockage\GIT\GitHub\smartest2\ui\ui_attribute_link.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AttributeLink(object):
    def setupUi(self, AttributeLink):
        AttributeLink.setObjectName("AttributeLink")
        AttributeLink.resize(750, 267)
        AttributeLink.setMinimumSize(QtCore.QSize(0, 30))
        AttributeLink.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gridLayout = QtWidgets.QGridLayout(AttributeLink)
        self.gridLayout.setContentsMargins(0, 2, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_bottom = QtWidgets.QWidget(AttributeLink)
        self.widget_bottom.setStyleSheet("QWidget#widget_bottom{background: #E9E7E3}")
        self.widget_bottom.setObjectName("widget_bottom")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_bottom)
        self.gridLayout_2.setContentsMargins(15, 10, 15, 10)
        self.gridLayout_2.setSpacing(10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.widget_bottom)
        self.label.setMinimumSize(QtCore.QSize(290, 26))
        self.label.setMaximumSize(QtCore.QSize(290, 26))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget_bottom)
        self.label_2.setMinimumSize(QtCore.QSize(50, 26))
        self.label_2.setMaximumSize(QtCore.QSize(50, 26))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.liste_composants = QtWidgets.QTreeView(self.widget_bottom)
        self.liste_composants.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.liste_composants.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.liste_composants.setAlternatingRowColors(True)
        self.liste_composants.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.liste_composants.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.liste_composants.setAnimated(True)
        self.liste_composants.setObjectName("liste_composants")
        self.gridLayout_2.addWidget(self.liste_composants, 0, 2, 2, 1)
        self.liste_composants.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.gridLayout.addWidget(self.widget_bottom, 1, 0, 1, 4)
        self.widget_top = QtWidgets.QWidget(AttributeLink)
        self.widget_top.setObjectName("widget_top")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_top)
        self.horizontalLayout.setContentsMargins(15, 7, 15, 7)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bt_type = QtWidgets.QPushButton(self.widget_top)
        self.bt_type.setEnabled(True)
        self.bt_type.setMinimumSize(QtCore.QSize(50, 26))
        self.bt_type.setMaximumSize(QtCore.QSize(50, 26))
        self.bt_type.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_type.setStyleSheet("QPushButton{border: 2px solid #416596; border-radius:5px;}")
        self.bt_type.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Images/link.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_type.setIcon(icon)
        self.bt_type.setIconSize(QtCore.QSize(20, 20))
        self.bt_type.setFlat(True)
        self.bt_type.setObjectName("bt_type")
        self.horizontalLayout.addWidget(self.bt_type)
        self.nom_attr = QtWidgets.QLabel(self.widget_top)
        self.nom_attr.setMinimumSize(QtCore.QSize(290, 26))
        self.nom_attr.setMaximumSize(QtCore.QSize(290, 26))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.nom_attr.setFont(font)
        self.nom_attr.setText("")
        self.nom_attr.setObjectName("nom_attr")
        self.horizontalLayout.addWidget(self.nom_attr)
        self.bt_afficher = QtWidgets.QPushButton(self.widget_top)
        self.bt_afficher.setMinimumSize(QtCore.QSize(0, 26))
        self.bt_afficher.setMaximumSize(QtCore.QSize(16777215, 26))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.bt_afficher.setFont(font)
        self.bt_afficher.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-radius:5px ; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #FFFFFF, stop:1 #BAD0E7)}\n"
"QPushButton:hover{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC)}\n"
"QPushButton:pressed{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8)}")
        self.bt_afficher.setObjectName("bt_afficher")
        self.horizontalLayout.addWidget(self.bt_afficher)
        self.gridLayout.addWidget(self.widget_top, 0, 0, 1, 4)

        self.retranslateUi(AttributeLink)
        QtCore.QMetaObject.connectSlotsByName(AttributeLink)
        AttributeLink.setTabOrder(self.bt_afficher, self.liste_composants)

    def retranslateUi(self, AttributeLink):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("AttributeLink", "Liste de ses composants"))
        self.bt_afficher.setText(_translate("AttributeLink", "Afficher l\'ouvrage"))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AttributeLink = QtWidgets.QWidget()
    ui = Ui_AttributeLink()
    ui.setupUi(AttributeLink)
    AttributeLink.show()
    sys.exit(app.exec_())
