# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Stockage\GIT\GitHub\smartest2\ui\ui_attribute_232.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Attribute232(object):
    def setupUi(self, Attribute232):
        Attribute232.setObjectName("Attribute232")
        Attribute232.resize(304, 140)
        Attribute232.setStyleSheet("QWidget#Attribute232 {background:#FFFFFF}")
        self.gridLayout = QtWidgets.QGridLayout(Attribute232)
        self.gridLayout.setContentsMargins(0, -1, 0, 0)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.list = QtWidgets.QListWidget(Attribute232)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.list.setFont(font)
        self.list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.list.setAlternatingRowColors(True)
        self.list.setObjectName("list")
        self.gridLayout.addWidget(self.list, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(9, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(9, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 1)
        self.fond = QtWidgets.QWidget(Attribute232)
        self.fond.setMinimumSize(QtCore.QSize(0, 38))
        self.fond.setMaximumSize(QtCore.QSize(16777215, 38))
        self.fond.setStyleSheet("QWidget#fond{background: #DBE4EE}")
        self.fond.setObjectName("fond")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.fond)
        self.horizontalLayout_3.setContentsMargins(-1, 0, 9, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.bt_valider = QtWidgets.QPushButton(self.fond)
        self.bt_valider.setMinimumSize(QtCore.QSize(120, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.bt_valider.setFont(font)
        self.bt_valider.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-radius: 5px ; padding-right: 10px; padding-left: 10px; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #FFFFFF, stop:1 #BAD0E7); }\n"
"QPushButton:hover{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC); }\n"
"QPushButton:pressed{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8); }")
        self.bt_valider.setIconSize(QtCore.QSize(18, 18))
        self.bt_valider.setShortcut("Ctrl+S")
        self.bt_valider.setObjectName("bt_valider")
        self.horizontalLayout_3.addWidget(self.bt_valider)
        self.bt_quitter = QtWidgets.QPushButton(self.fond)
        self.bt_quitter.setMinimumSize(QtCore.QSize(120, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.bt_quitter.setFont(font)
        self.bt_quitter.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-radius: 5px ; padding-right: 10px; padding-left: 10px; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #FFFFFF, stop:1 #BAD0E7); }\n"
"QPushButton:hover{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC); }\n"
"QPushButton:pressed{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8); }")
        self.bt_quitter.setIconSize(QtCore.QSize(18, 18))
        self.bt_quitter.setShortcut("Esc")
        self.bt_quitter.setObjectName("bt_quitter")
        self.horizontalLayout_3.addWidget(self.bt_quitter)
        self.gridLayout.addWidget(self.fond, 1, 0, 1, 3)

        self.retranslateUi(Attribute232)
        self.list.setCurrentRow(-1)
        QtCore.QMetaObject.connectSlotsByName(Attribute232)

    def retranslateUi(self, Attribute232):
        _translate = QtCore.QCoreApplication.translate
        self.bt_valider.setText(_translate("Attribute232", " Valider"))
        self.bt_quitter.setText(_translate("Attribute232", " Annuler"))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Attribute232 = QtWidgets.QWidget()
    ui = Ui_Attribute232()
    ui.setupUi(Attribute232)
    Attribute232.show()
    sys.exit(app.exec_())
