# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Stockage\GIT\GitHub\smartest2\ui\ui_attribute_235.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Attribute235(object):
    def setupUi(self, Attribute235):
        Attribute235.setObjectName("Attribute235")
        Attribute235.resize(646, 380)
        self.bt_su = QtWidgets.QPushButton(Attribute235)
        self.bt_su.setGeometry(QtCore.QRect(34, 47, 42, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.bt_su.setFont(font)
        self.bt_su.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-radius:5px ; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #FFFFFF, stop:1 #BAD0E7); }\n"
"QPushButton:checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8); }\n"
"QPushButton:hover:!checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC); }\n"
"QPushButton:hover::checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #BAD0E7, stop:1 #FFFFFF); }")
        self.bt_su.setCheckable(True)
        self.bt_su.setObjectName("bt_su")
        self.buttonGroup = QtWidgets.QButtonGroup(Attribute235)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.bt_su)
        self.bt_sit = QtWidgets.QPushButton(Attribute235)
        self.bt_sit.setGeometry(QtCore.QRect(34, 272, 42, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.bt_sit.setFont(font)
        self.bt_sit.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-radius:5px ; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #FFFFFF, stop:1 #BAD0E7); }\n"
"QPushButton:checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8); }\n"
"QPushButton:hover:!checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC); }\n"
"QPushButton:hover::checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #BAD0E7, stop:1 #FFFFFF); }")
        self.bt_sit.setCheckable(True)
        self.bt_sit.setObjectName("bt_sit")
        self.buttonGroup.addButton(self.bt_sit)
        self.bt_sd = QtWidgets.QPushButton(Attribute235)
        self.bt_sd.setGeometry(QtCore.QRect(34, 304, 42, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.bt_sd.setFont(font)
        self.bt_sd.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-radius:5px ; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #FFFFFF, stop:1 #BAD0E7); }\n"
"QPushButton:checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8); }\n"
"QPushButton:hover:!checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC); }\n"
"QPushButton:hover::checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #BAD0E7, stop:1 #FFFFFF); }")
        self.bt_sd.setCheckable(True)
        self.bt_sd.setObjectName("bt_sd")
        self.buttonGroup.addButton(self.bt_sd)
        self.bt_su1 = QtWidgets.QPushButton(Attribute235)
        self.bt_su1.setGeometry(QtCore.QRect(565, 48, 56, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.bt_su1.setFont(font)
        self.bt_su1.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-radius:5px ; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #FFFFFF, stop:1 #BAD0E7); }\n"
"QPushButton:checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8); }\n"
"QPushButton:hover:!checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC); }\n"
"QPushButton:hover::checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #BAD0E7, stop:1 #FFFFFF); }")
        self.bt_su1.setCheckable(True)
        self.bt_su1.setObjectName("bt_su1")
        self.buttonGroup.addButton(self.bt_su1)
        self.bt_su2 = QtWidgets.QPushButton(Attribute235)
        self.bt_su2.setGeometry(QtCore.QRect(565, 79, 56, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.bt_su2.setFont(font)
        self.bt_su2.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-radius:5px ; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #FFFFFF, stop:1 #BAD0E7); }\n"
"QPushButton:checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8); }\n"
"QPushButton:hover:!checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC); }\n"
"QPushButton:hover::checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #BAD0E7, stop:1 #FFFFFF); }")
        self.bt_su2.setCheckable(True)
        self.bt_su2.setObjectName("bt_su2")
        self.buttonGroup.addButton(self.bt_su2)
        self.bt_su3 = QtWidgets.QPushButton(Attribute235)
        self.bt_su3.setGeometry(QtCore.QRect(565, 111, 56, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.bt_su3.setFont(font)
        self.bt_su3.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-radius:5px ; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #FFFFFF, stop:1 #BAD0E7); }\n"
"QPushButton:checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8); }\n"
"QPushButton:hover:!checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC); }\n"
"QPushButton:hover::checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #BAD0E7, stop:1 #FFFFFF); }")
        self.bt_su3.setCheckable(True)
        self.bt_su3.setObjectName("bt_su3")
        self.buttonGroup.addButton(self.bt_su3)
        self.bt_su4 = QtWidgets.QPushButton(Attribute235)
        self.bt_su4.setGeometry(QtCore.QRect(565, 143, 56, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.bt_su4.setFont(font)
        self.bt_su4.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-radius:5px ; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #FFFFFF, stop:1 #BAD0E7); }\n"
"QPushButton:checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8); }\n"
"QPushButton:hover:!checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC); }\n"
"QPushButton:hover::checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #BAD0E7, stop:1 #FFFFFF); }")
        self.bt_su4.setCheckable(True)
        self.bt_su4.setObjectName("bt_su4")
        self.buttonGroup.addButton(self.bt_su4)
        self.bt_su5 = QtWidgets.QPushButton(Attribute235)
        self.bt_su5.setGeometry(QtCore.QRect(565, 175, 56, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.bt_su5.setFont(font)
        self.bt_su5.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-radius:5px ; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #FFFFFF, stop:1 #BAD0E7); }\n"
"QPushButton:checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8); }\n"
"QPushButton:hover:!checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC); }\n"
"QPushButton:hover::checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #BAD0E7, stop:1 #FFFFFF); }")
        self.bt_su5.setCheckable(True)
        self.bt_su5.setObjectName("bt_su5")
        self.buttonGroup.addButton(self.bt_su5)
        self.bt_su6 = QtWidgets.QPushButton(Attribute235)
        self.bt_su6.setGeometry(QtCore.QRect(565, 207, 56, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.bt_su6.setFont(font)
        self.bt_su6.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-radius:5px ; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #FFFFFF, stop:1 #BAD0E7); }\n"
"QPushButton:checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8); }\n"
"QPushButton:hover:!checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC); }\n"
"QPushButton:hover::checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #BAD0E7, stop:1 #FFFFFF); }")
        self.bt_su6.setCheckable(True)
        self.bt_su6.setObjectName("bt_su6")
        self.buttonGroup.addButton(self.bt_su6)
        self.bt_su7 = QtWidgets.QPushButton(Attribute235)
        self.bt_su7.setGeometry(QtCore.QRect(565, 239, 56, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.bt_su7.setFont(font)
        self.bt_su7.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-radius:5px ; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #FFFFFF, stop:1 #BAD0E7); }\n"
"QPushButton:checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8); }\n"
"QPushButton:hover:!checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC); }\n"
"QPushButton:hover::checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #BAD0E7, stop:1 #FFFFFF); }")
        self.bt_su7.setCheckable(True)
        self.bt_su7.setObjectName("bt_su7")
        self.buttonGroup.addButton(self.bt_su7)
        self.bt_st = QtWidgets.QPushButton(Attribute235)
        self.bt_st.setGeometry(QtCore.QRect(565, 271, 56, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.bt_st.setFont(font)
        self.bt_st.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-radius:5px ; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #FFFFFF, stop:1 #BAD0E7); }\n"
"QPushButton:checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8); }\n"
"QPushButton:hover:!checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC); }\n"
"QPushButton:hover::checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #BAD0E7, stop:1 #FFFFFF); }")
        self.bt_st.setCheckable(True)
        self.bt_st.setObjectName("bt_st")
        self.buttonGroup.addButton(self.bt_st)
        self.bt_sd2 = QtWidgets.QPushButton(Attribute235)
        self.bt_sd2.setGeometry(QtCore.QRect(565, 303, 56, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.bt_sd2.setFont(font)
        self.bt_sd2.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-radius:5px ; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #FFFFFF, stop:1 #BAD0E7); }\n"
"QPushButton:checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8); }\n"
"QPushButton:hover:!checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC); }\n"
"QPushButton:hover::checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #BAD0E7, stop:1 #FFFFFF); }")
        self.bt_sd2.setCheckable(True)
        self.bt_sd2.setObjectName("bt_sd2")
        self.buttonGroup.addButton(self.bt_sd2)
        self.fond = QtWidgets.QWidget(Attribute235)
        self.fond.setGeometry(QtCore.QRect(0, 342, 646, 38))
        self.fond.setMinimumSize(QtCore.QSize(0, 38))
        self.fond.setMaximumSize(QtCore.QSize(16777215, 38))
        self.fond.setStyleSheet("QWidget#fond{background: #DBE4EE}")
        self.fond.setObjectName("fond")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.fond)
        self.horizontalLayout_3.setContentsMargins(0, 0, 9, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.bt_valider = QtWidgets.QPushButton(self.fond)
        self.bt_valider.setMinimumSize(QtCore.QSize(120, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.bt_valider.setFont(font)
        self.bt_valider.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-radius: 5px ; padding-right: 10px; padding-left: 10px; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #FFFFFF, stop:1 #BAD0E7); }\n"
"QPushButton:hover{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC); }\n"
"QPushButton:pressed{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8); }")
        self.bt_valider.setIconSize(QtCore.QSize(18, 18))
        self.bt_valider.setShortcut("Ctrl+S")
        self.bt_valider.setObjectName("bt_valider")
        self.horizontalLayout_3.addWidget(self.bt_valider)
        self.bt_quitter = QtWidgets.QPushButton(self.fond)
        self.bt_quitter.setMinimumSize(QtCore.QSize(120, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.bt_quitter.setFont(font)
        self.bt_quitter.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-radius: 5px ; padding-right: 10px; padding-left: 10px; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #FFFFFF, stop:1 #BAD0E7); }\n"
"QPushButton:hover{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC); }\n"
"QPushButton:pressed{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8); }")
        self.bt_quitter.setIconSize(QtCore.QSize(18, 18))
        self.bt_quitter.setShortcut("Esc")
        self.bt_quitter.setObjectName("bt_quitter")
        self.horizontalLayout_3.addWidget(self.bt_quitter)

        self.retranslateUi(Attribute235)
        QtCore.QMetaObject.connectSlotsByName(Attribute235)
        Attribute235.setTabOrder(self.bt_su, self.bt_su1)
        Attribute235.setTabOrder(self.bt_su1, self.bt_su2)
        Attribute235.setTabOrder(self.bt_su2, self.bt_su3)
        Attribute235.setTabOrder(self.bt_su3, self.bt_su4)
        Attribute235.setTabOrder(self.bt_su4, self.bt_su5)
        Attribute235.setTabOrder(self.bt_su5, self.bt_su6)
        Attribute235.setTabOrder(self.bt_su6, self.bt_su7)
        Attribute235.setTabOrder(self.bt_su7, self.bt_sit)
        Attribute235.setTabOrder(self.bt_sit, self.bt_st)
        Attribute235.setTabOrder(self.bt_st, self.bt_sd)
        Attribute235.setTabOrder(self.bt_sd, self.bt_sd2)
        Attribute235.setTabOrder(self.bt_sd2, self.bt_valider)
        Attribute235.setTabOrder(self.bt_valider, self.bt_quitter)

    def retranslateUi(self, Attribute235):
        _translate = QtCore.QCoreApplication.translate
        self.bt_valider.setText(_translate("Attribute235", " Valider"))
        self.bt_quitter.setText(_translate("Attribute235", " Annuler"))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Attribute235 = QtWidgets.QWidget()
    ui = Ui_Attribute235()
    ui.setupUi(Attribute235)
    Attribute235.show()
    sys.exit(app.exec_())
