# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Stockage\GIT\GitHub\smartest2\ui\ui_attribute_231.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Attribute231(object):
    def setupUi(self, Attribute231):
        Attribute231.setObjectName("Attribute231")
        Attribute231.resize(323, 463)
        self.bt_r_etage_2 = QtWidgets.QPushButton(Attribute231)
        self.bt_r_etage_2.setGeometry(QtCore.QRect(88, 147, 45, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.bt_r_etage_2.setFont(font)
        self.bt_r_etage_2.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-radius:5px ; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #FFFFFF, stop:1 #BAD0E7); }\n"
"QPushButton:checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8); }\n"
"QPushButton:hover:!checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC); }\n"
"QPushButton:hover::checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #BAD0E7, stop:1 #FFFFFF); }")
        self.bt_r_etage_2.setCheckable(True)
        self.bt_r_etage_2.setObjectName("bt_r_etage_2")
        self.buttonGroup = QtWidgets.QButtonGroup(Attribute231)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.bt_r_etage_2)
        self.bt_r_etage_22 = QtWidgets.QPushButton(Attribute231)
        self.bt_r_etage_22.setGeometry(QtCore.QRect(186, 147, 45, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.bt_r_etage_22.setFont(font)
        self.bt_r_etage_22.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-radius:5px ; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #FFFFFF, stop:1 #BAD0E7); }\n"
"QPushButton:checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8); }\n"
"QPushButton:hover:!checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC); }\n"
"QPushButton:hover::checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #BAD0E7, stop:1 #FFFFFF); }")
        self.bt_r_etage_22.setCheckable(True)
        self.bt_r_etage_22.setObjectName("bt_r_etage_22")
        self.buttonGroup.addButton(self.bt_r_etage_22)
        self.bt_r_etage_11 = QtWidgets.QPushButton(Attribute231)
        self.bt_r_etage_11.setGeometry(QtCore.QRect(88, 214, 45, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.bt_r_etage_11.setFont(font)
        self.bt_r_etage_11.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-radius:5px ; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #FFFFFF, stop:1 #BAD0E7); }\n"
"QPushButton:checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8); }\n"
"QPushButton:hover:!checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC); }\n"
"QPushButton:hover::checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #BAD0E7, stop:1 #FFFFFF); }")
        self.bt_r_etage_11.setCheckable(True)
        self.bt_r_etage_11.setObjectName("bt_r_etage_11")
        self.buttonGroup.addButton(self.bt_r_etage_11)
        self.bt_r_etage_12 = QtWidgets.QPushButton(Attribute231)
        self.bt_r_etage_12.setGeometry(QtCore.QRect(186, 214, 45, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.bt_r_etage_12.setFont(font)
        self.bt_r_etage_12.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-radius:5px ; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #FFFFFF, stop:1 #BAD0E7); }\n"
"QPushButton:checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8); }\n"
"QPushButton:hover:!checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC); }\n"
"QPushButton:hover::checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #BAD0E7, stop:1 #FFFFFF); }")
        self.bt_r_etage_12.setCheckable(True)
        self.bt_r_etage_12.setObjectName("bt_r_etage_12")
        self.buttonGroup.addButton(self.bt_r_etage_12)
        self.bt_r_rdc = QtWidgets.QPushButton(Attribute231)
        self.bt_r_rdc.setGeometry(QtCore.QRect(88, 280, 45, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.bt_r_rdc.setFont(font)
        self.bt_r_rdc.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-radius:5px ; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #FFFFFF, stop:1 #BAD0E7); }\n"
"QPushButton:checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8); }\n"
"QPushButton:hover:!checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC); }\n"
"QPushButton:hover::checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #BAD0E7, stop:1 #FFFFFF); }")
        self.bt_r_rdc.setCheckable(True)
        self.bt_r_rdc.setObjectName("bt_r_rdc")
        self.buttonGroup.addButton(self.bt_r_rdc)
        self.bt_r_garage = QtWidgets.QPushButton(Attribute231)
        self.bt_r_garage.setGeometry(QtCore.QRect(186, 280, 45, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.bt_r_garage.setFont(font)
        self.bt_r_garage.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-radius:5px ; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #FFFFFF, stop:1 #BAD0E7); }\n"
"QPushButton:checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8); }\n"
"QPushButton:hover:!checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC); }\n"
"QPushButton:hover::checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #BAD0E7, stop:1 #FFFFFF); }")
        self.bt_r_garage.setCheckable(True)
        self.bt_r_garage.setObjectName("bt_r_garage")
        self.buttonGroup.addButton(self.bt_r_garage)
        self.bt_s_loggia = QtWidgets.QPushButton(Attribute231)
        self.bt_s_loggia.setGeometry(QtCore.QRect(261, 214, 45, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.bt_s_loggia.setFont(font)
        self.bt_s_loggia.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-radius:5px ; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #FFFFFF, stop:1 #BAD0E7); }\n"
"QPushButton:checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8); }\n"
"QPushButton:hover:!checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC); }\n"
"QPushButton:hover::checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #BAD0E7, stop:1 #FFFFFF); }")
        self.bt_s_loggia.setCheckable(True)
        self.bt_s_loggia.setObjectName("bt_s_loggia")
        self.buttonGroup.addButton(self.bt_s_loggia)
        self.bt_s_balcon = QtWidgets.QPushButton(Attribute231)
        self.bt_s_balcon.setGeometry(QtCore.QRect(261, 147, 45, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.bt_s_balcon.setFont(font)
        self.bt_s_balcon.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-radius:5px ; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #FFFFFF, stop:1 #BAD0E7); }\n"
"QPushButton:checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8); }\n"
"QPushButton:hover:!checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC); }\n"
"QPushButton:hover::checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #BAD0E7, stop:1 #FFFFFF); }")
        self.bt_s_balcon.setCheckable(True)
        self.bt_s_balcon.setObjectName("bt_s_balcon")
        self.buttonGroup.addButton(self.bt_s_balcon)
        self.bt_s_ext = QtWidgets.QPushButton(Attribute231)
        self.bt_s_ext.setGeometry(QtCore.QRect(7, 249, 45, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.bt_s_ext.setFont(font)
        self.bt_s_ext.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-radius:5px ; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #FFFFFF, stop:1 #BAD0E7); }\n"
"QPushButton:checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8); }\n"
"QPushButton:hover:!checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC); }\n"
"QPushButton:hover::checked{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #BAD0E7, stop:1 #FFFFFF); }")
        self.bt_s_ext.setCheckable(True)
        self.bt_s_ext.setObjectName("bt_s_ext")
        self.buttonGroup.addButton(self.bt_s_ext)
        self.fond = QtWidgets.QWidget(Attribute231)
        self.fond.setGeometry(QtCore.QRect(0, 425, 323, 38))
        self.fond.setMinimumSize(QtCore.QSize(0, 38))
        self.fond.setMaximumSize(QtCore.QSize(16777215, 38))
        self.fond.setStyleSheet("QWidget#fond{background: #DBE4EE}")
        self.fond.setObjectName("fond")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.fond)
        self.horizontalLayout_3.setContentsMargins(0, 0, 9, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.bt_valider = QtWidgets.QPushButton(self.fond)
        self.bt_valider.setMinimumSize(QtCore.QSize(120, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.bt_valider.setFont(font)
        self.bt_valider.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-radius: 5px ; padding-right: 10px; padding-left: 10px; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #FFFFFF, stop:1 #BAD0E7); }\n"
"QPushButton:hover{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC); }\n"
"QPushButton:pressed{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8); }")
        self.bt_valider.setIconSize(QtCore.QSize(18, 18))
        self.bt_valider.setShortcut("Ctrl+S")
        self.bt_valider.setObjectName("bt_valider")
        self.horizontalLayout_3.addWidget(self.bt_valider)
        self.bt_quitter = QtWidgets.QPushButton(self.fond)
        self.bt_quitter.setMinimumSize(QtCore.QSize(120, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.bt_quitter.setFont(font)
        self.bt_quitter.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-radius: 5px ; padding-right: 10px; padding-left: 10px; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #FFFFFF, stop:1 #BAD0E7); }\n"
"QPushButton:hover{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC); }\n"
"QPushButton:pressed{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8); }")
        self.bt_quitter.setIconSize(QtCore.QSize(18, 18))
        self.bt_quitter.setShortcut("Esc")
        self.bt_quitter.setObjectName("bt_quitter")
        self.horizontalLayout_3.addWidget(self.bt_quitter)

        self.retranslateUi(Attribute231)
        QtCore.QMetaObject.connectSlotsByName(Attribute231)
        Attribute231.setTabOrder(self.bt_r_etage_2, self.bt_r_etage_22)
        Attribute231.setTabOrder(self.bt_r_etage_22, self.bt_s_balcon)
        Attribute231.setTabOrder(self.bt_s_balcon, self.bt_r_etage_11)
        Attribute231.setTabOrder(self.bt_r_etage_11, self.bt_r_etage_12)
        Attribute231.setTabOrder(self.bt_r_etage_12, self.bt_s_loggia)
        Attribute231.setTabOrder(self.bt_s_loggia, self.bt_s_ext)
        Attribute231.setTabOrder(self.bt_s_ext, self.bt_r_rdc)
        Attribute231.setTabOrder(self.bt_r_rdc, self.bt_r_garage)
        Attribute231.setTabOrder(self.bt_r_garage, self.bt_valider)
        Attribute231.setTabOrder(self.bt_valider, self.bt_quitter)

    def retranslateUi(self, Attribute231):
        _translate = QtCore.QCoreApplication.translate
        self.bt_valider.setText(_translate("Attribute231", " Valider"))
        self.bt_quitter.setText(_translate("Attribute231", " Annuler"))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Attribute231 = QtWidgets.QWidget()
    ui = Ui_Attribute231()
    ui.setupUi(Attribute231)
    Attribute231.show()
    sys.exit(app.exec_())
