# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Stockage\GIT\GitHub\smartest2\ui\ui_attribute_335.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Attribute335(object):
    def setupUi(self, Attribute335):
        Attribute335.setObjectName("Attribute335")
        Attribute335.resize(750, 40)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Attribute335.sizePolicy().hasHeightForWidth())
        Attribute335.setSizePolicy(sizePolicy)
        Attribute335.setMinimumSize(QtCore.QSize(575, 40))
        Attribute335.setMaximumSize(QtCore.QSize(16777215, 40))
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(Attribute335)
        self.horizontalLayout_3.setContentsMargins(15, 2, 15, 2)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.num_attrib = QtWidgets.QLabel(Attribute335)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_attrib.sizePolicy().hasHeightForWidth())
        self.num_attrib.setSizePolicy(sizePolicy)
        self.num_attrib.setMinimumSize(QtCore.QSize(50, 26))
        self.num_attrib.setMaximumSize(QtCore.QSize(50, 26))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.num_attrib.setFont(font)
        self.num_attrib.setStyleSheet("QLabel{border: 2px solid #416596; border-radius: 5px; color: #416596; }")
        self.num_attrib.setAlignment(QtCore.Qt.AlignCenter)
        self.num_attrib.setObjectName("num_attrib")
        self.horizontalLayout_3.addWidget(self.num_attrib)
        self.name_attrib = QtWidgets.QLabel(Attribute335)
        self.name_attrib.setMinimumSize(QtCore.QSize(240, 26))
        self.name_attrib.setMaximumSize(QtCore.QSize(240, 26))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.name_attrib.setFont(font)
        self.name_attrib.setObjectName("name_attrib")
        self.horizontalLayout_3.addWidget(self.name_attrib)
        self.type_attrib = QtWidgets.QLabel(Attribute335)
        self.type_attrib.setMinimumSize(QtCore.QSize(40, 26))
        self.type_attrib.setMaximumSize(QtCore.QSize(40, 26))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.type_attrib.setFont(font)
        self.type_attrib.setStyleSheet("QLabel{color: grey; }")
        self.type_attrib.setText("ABC")
        self.type_attrib.setAlignment(QtCore.Qt.AlignCenter)
        self.type_attrib.setObjectName("type_attrib")
        self.horizontalLayout_3.addWidget(self.type_attrib)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.value_attrib = QtWidgets.QLineEdit(Attribute335)
        self.value_attrib.setMinimumSize(QtCore.QSize(0, 26))
        self.value_attrib.setMaximumSize(QtCore.QSize(16777215, 26))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.value_attrib.setFont(font)
        self.value_attrib.setStyleSheet("QLineEdit{padding-left: 5px; border: 1px solid #8f8f91; border-right-width: 0px; border-top-left-radius:5px; border-bottom-left-radius: 5px; }")
        self.value_attrib.setReadOnly(False)
        self.value_attrib.setObjectName("value_attrib")
        self.horizontalLayout.addWidget(self.value_attrib)
        self.preview_bt = QtWidgets.QPushButton(Attribute335)
        self.preview_bt.setMinimumSize(QtCore.QSize(40, 26))
        self.preview_bt.setMaximumSize(QtCore.QSize(40, 26))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.preview_bt.setFont(font)
        self.preview_bt.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-left-width: 0px; padding-left: 1px; border-right-width: 0px; padding-right: 1px; background-color:#FFFFFF; }\n"
"QPushButton:hover{border-left-width: 1px; border-right-width: 1px; padding: 0px; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC); }\n"
"QPushButton:pressed{border-left-width: 1px; border-right-width: 1px; padding: 0px; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8); }")
        self.preview_bt.setText("")
        self.preview_bt.setIconSize(QtCore.QSize(20, 20))
        self.preview_bt.setFlat(True)
        self.preview_bt.setObjectName("preview_bt")
        self.horizontalLayout.addWidget(self.preview_bt)
        self.browser_bt = QtWidgets.QPushButton(Attribute335)
        self.browser_bt.setMinimumSize(QtCore.QSize(40, 26))
        self.browser_bt.setMaximumSize(QtCore.QSize(40, 26))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.browser_bt.setFont(font)
        self.browser_bt.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.browser_bt.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-left-width: 0px; padding-left: 1px;  border-top-right-radius: 5px ; border-bottom-right-radius: 5px; background-color:#FFFFFF; }\n"
"QPushButton:hover{border-left-width: 1px; padding: 0px; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC); }\n"
"QPushButton:pressed{border-left-width: 1px; padding: 0px; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8); }")
        self.browser_bt.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Images/surface.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.browser_bt.setIcon(icon)
        self.browser_bt.setIconSize(QtCore.QSize(20, 20))
        self.browser_bt.setFlat(True)
        self.browser_bt.setObjectName("browser_bt")
        self.horizontalLayout.addWidget(self.browser_bt)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)

        self.retranslateUi(Attribute335)
        QtCore.QMetaObject.connectSlotsByName(Attribute335)

    def retranslateUi(self, Attribute335):
        _translate = QtCore.QCoreApplication.translate
        self.num_attrib.setToolTip(_translate("Attribute335", "Attribut Allplan"))
        self.type_attrib.setToolTip(_translate("Attribute335", "Texte"))
        self.preview_bt.setToolTip(_translate("Attribute335", "Afficher l\'aperçu de la texture"))
        self.browser_bt.setToolTip(_translate("Attribute335", "Choisir texture"))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Attribute335 = QtWidgets.QWidget()
    ui = Ui_Attribute335()
    ui.setupUi(Attribute335)
    Attribute335.show()
    sys.exit(app.exec_())
