# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Stockage\GIT\GitHub\smartest2\ui\ui_attribute_code.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AttributeCode(object):
    def setupUi(self, AttributeCode):
        AttributeCode.setObjectName("AttributeCode")
        AttributeCode.resize(750, 40)
        AttributeCode.setMinimumSize(QtCore.QSize(575, 40))
        AttributeCode.setMaximumSize(QtCore.QSize(16777215, 40))
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(AttributeCode)
        self.horizontalLayout_3.setContentsMargins(15, 2, 15, 2)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.num_attrib = QtWidgets.QLabel(AttributeCode)
        self.num_attrib.setMinimumSize(QtCore.QSize(50, 26))
        self.num_attrib.setMaximumSize(QtCore.QSize(50, 26))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.num_attrib.setFont(font)
        self.num_attrib.setStyleSheet("QLabel{background-color:#ffeebf; border: 2px solid #416596; border-radius: 5px; color: #416596}")
        self.num_attrib.setAlignment(QtCore.Qt.AlignCenter)
        self.num_attrib.setObjectName("num_attrib")
        self.horizontalLayout_3.addWidget(self.num_attrib)
        self.name_attrib = QtWidgets.QLabel(AttributeCode)
        self.name_attrib.setMinimumSize(QtCore.QSize(240, 26))
        self.name_attrib.setMaximumSize(QtCore.QSize(240, 26))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.name_attrib.setFont(font)
        self.name_attrib.setText("")
        self.name_attrib.setObjectName("name_attrib")
        self.horizontalLayout_3.addWidget(self.name_attrib)
        self.type_attrib = QtWidgets.QLabel(AttributeCode)
        self.type_attrib.setMinimumSize(QtCore.QSize(40, 26))
        self.type_attrib.setMaximumSize(QtCore.QSize(40, 26))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.type_attrib.setFont(font)
        self.type_attrib.setStyleSheet("QLabel{color: grey; }")
        self.type_attrib.setText("ABC")
        self.type_attrib.setAlignment(QtCore.Qt.AlignCenter)
        self.type_attrib.setObjectName("type_attrib")
        self.horizontalLayout_3.addWidget(self.type_attrib)
        self.lineedit_layer = QtWidgets.QHBoxLayout()
        self.lineedit_layer.setSpacing(0)
        self.lineedit_layer.setObjectName("lineedit_layer")
        self.value_attrib = QtWidgets.QLineEdit(AttributeCode)
        self.value_attrib.setMinimumSize(QtCore.QSize(100, 26))
        self.value_attrib.setMaximumSize(QtCore.QSize(16777215, 26))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.value_attrib.setFont(font)
        self.value_attrib.setStyleSheet("QLineEdit{padding-left: 5px; border: 1px solid #8f8f91; border-right-width: 0px; border-top-left-radius:5px; border-bottom-left-radius: 5px; }")
        self.value_attrib.setObjectName("value_attrib")
        self.lineedit_layer.addWidget(self.value_attrib)
        self.verification_bt = QtWidgets.QPushButton(AttributeCode)
        self.verification_bt.setMinimumSize(QtCore.QSize(40, 26))
        self.verification_bt.setMaximumSize(QtCore.QSize(40, 26))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.verification_bt.setFont(font)
        self.verification_bt.setFocusPolicy(QtCore.Qt.NoFocus)
        self.verification_bt.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-left-width: 0px; padding-left: 1px; border-right-width: 0px; padding-right: 1px; background-color:#FFFFFF; }\n"
"QPushButton:hover{border-left-width: 1px; border-right-width: 1px; padding: 0px; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC); }\n"
"QPushButton:pressed{border-left-width: 1px; border-right-width: 1px; padding: 0px; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8); }")
        self.verification_bt.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Images/test_verifier.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.verification_bt.setIcon(icon)
        self.verification_bt.setIconSize(QtCore.QSize(16, 16))
        self.verification_bt.setFlat(True)
        self.verification_bt.setObjectName("verification_bt")
        self.lineedit_layer.addWidget(self.verification_bt)
        self.formatting_bt = QtWidgets.QPushButton(AttributeCode)
        self.formatting_bt.setMinimumSize(QtCore.QSize(40, 26))
        self.formatting_bt.setMaximumSize(QtCore.QSize(40, 26))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.formatting_bt.setFont(font)
        self.formatting_bt.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-left-width: 0px; padding-left: 1px;  border-top-right-radius: 5px ; border-bottom-right-radius: 5px; background-color:#FFFFFF; }\n"
"QPushButton:hover{border-left-width: 1px; padding: 0px; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC); }\n"
"QPushButton:pressed{border-left-width: 1px; padding: 0px; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8); }")
        self.formatting_bt.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Images/format.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.formatting_bt.setIcon(icon1)
        self.formatting_bt.setIconSize(QtCore.QSize(16, 16))
        self.formatting_bt.setFlat(True)
        self.formatting_bt.setObjectName("formatting_bt")
        self.lineedit_layer.addWidget(self.formatting_bt)
        self.horizontalLayout_3.addLayout(self.lineedit_layer)

        self.retranslateUi(AttributeCode)
        QtCore.QMetaObject.connectSlotsByName(AttributeCode)

    def retranslateUi(self, AttributeCode):
        _translate = QtCore.QCoreApplication.translate
        self.num_attrib.setToolTip(_translate("AttributeCode", "Attribut Allplan"))
        self.type_attrib.setToolTip(_translate("AttributeCode", "Texte"))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AttributeCode = QtWidgets.QWidget()
    ui = Ui_AttributeCode()
    ui.setupUi(AttributeCode)
    AttributeCode.show()
    sys.exit(app.exec_())
