# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Stockage\GIT\GitHub\smartest2\ui\ui_calendar.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Calendar(object):
    def setupUi(self, Calendar):
        Calendar.setObjectName("Calendar")
        Calendar.setWindowModality(QtCore.Qt.ApplicationModal)
        Calendar.resize(400, 260)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Images/asc.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Calendar.setWindowIcon(icon)
        Calendar.setStyleSheet("QWidget#Calendar {background:#FFFFFF}")
        self.calendrier_layer = QtWidgets.QGridLayout(Calendar)
        self.calendrier_layer.setVerticalSpacing(15)
        self.calendrier_layer.setObjectName("calendrier_layer")
        self.calendar_widget = QtWidgets.QCalendarWidget(Calendar)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.calendar_widget.setFont(font)
        self.calendar_widget.setStyleSheet("#calendar_widget QWidget {alternate-background-color: #DBE4EE; }\n"
"\n"
"/*----------------*/\n"
"\n"
"#qt_calendar_navigationbar {background-color: #FFFFFF; border: 1px solid #8f8f91; border-bottom-width: 0px; border-top-left-radius:5px; border-top-right-radius: 5px; }\n"
"\n"
"/*----------------*/\n"
"\n"
"#qt_calendar_prevmonth { border: none; qproperty-icon: none; image: url(:/Images/calendar_down.svg);\n"
"min-width: 20 px;  min-height: 20 px; border-top-left-radius: 5px; background-color: transparent; padding: 5px; margin-right: 5px; }\n"
"\n"
"#qt_calendar_prevmonth:hover {border: 1px solid #8f8f91; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC); }\n"
"\n"
"#qt_calendar_prevmonth:pressed {border: 1px solid #8f8f91;  background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8); }\n"
"\n"
"/*----------------*/\n"
"\n"
"#qt_calendar_monthbutton, #qt_calendar_yearbutton {color: #000; padding: 5px;  min-height: 20 px;  font-size: 13px; }\n"
"#qt_calendar_monthbutton {width: 110 px; }\n"
"#qt_calendar_monthbutton:hover, #qt_calendar_yearbutton:hover {border: 1px solid #8f8f91; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC); }\n"
"\n"
"#qt_calendar_monthbutton:pressed, #qt_calendar_yearbutton:pressed {border: 1px solid #8f8f91;  background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8); }\n"
"\n"
"/*----------------*/\n"
"\n"
"#qt_calendar_yearedit {color: #000; background-color: transparent;  padding: 5px; font-size: 13px; }\n"
"\n"
"/*----------------*/\n"
"\n"
"#qt_calendar_nextmonth { border: none; qproperty-icon: none; image: url(:/Images/calendar_up.svg);\n"
"min-width: 20 px;  min-height: 20 px; border-top-right-radius: 5px; background-color: transparent; padding: 5px; margin-left: 5px; }\n"
"\n"
"#qt_calendar_nextmonth:hover {border: 1px solid #8f8f91; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC); }\n"
"\n"
"#qt_calendar_nextmonth:pressed {border: 1px solid #8f8f91;  background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8); }\n"
"\n"
"/*----------------*/\n"
"\n"
"#calendar_widget QToolButton QMenu{background-color: #fff; width: 125 px; border: 1px solid #8f8f91}\n"
"\n"
"#calendar_widget QToolButton QMenu::item {padding-bottom: 1px; padding-left: 5px; padding-right: 5px; width: 114 px; }\n"
"\n"
"#calendar_widget QToolButton QMenu::item:selected {background-color: #BAD0E7; }\n"
"\n"
"#calendar_widget QToolButton::menu-indicator {nosubcontrol-origin: margin; subcontrol-position: right center; margin-top: 10 px; width: 20px; }\n"
"\n"
"/*----------------*/\n"
"\n"
"#qt_calendar_calendarview {border: 1px solid #8f8f91; selection-background-color: #DBE4EE; selection-color: #000}\n"
"\n"
"")
        self.calendar_widget.setGridVisible(False)
        self.calendar_widget.setObjectName("calendar_widget")
        self.calendrier_layer.addWidget(self.calendar_widget, 0, 0, 1, 2)
        self.today = QtWidgets.QPushButton(Calendar)
        self.today.setMinimumSize(QtCore.QSize(0, 24))
        self.today.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-radius: 5px ; padding-right: 10px; padding-left: 10px; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #FFFFFF, stop:1 #BAD0E7); }\n"
"QPushButton:hover{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC); }\n"
"QPushButton:pressed{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8); }")
        self.today.setObjectName("today")
        self.calendrier_layer.addWidget(self.today, 1, 0, 1, 2)

        self.retranslateUi(Calendar)
        QtCore.QMetaObject.connectSlotsByName(Calendar)

    def retranslateUi(self, Calendar):
        _translate = QtCore.QCoreApplication.translate
        Calendar.setWindowTitle(_translate("Calendar", "Calendrier"))
        self.today.setToolTip(_translate("Calendar", "Afficher la date du jour"))
        self.today.setText(_translate("Calendar", "Aujourd\'hui"))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Calendar = QtWidgets.QWidget()
    ui = Ui_Calendar()
    ui.setupUi(Calendar)
    Calendar.show()
    sys.exit(app.exec_())
