# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Stockage\GIT\GitHub\smartest2\ui\ui_formula_tool.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WidgetFormulaTool(object):
    def setupUi(self, WidgetFormulaTool):
        WidgetFormulaTool.setObjectName("WidgetFormulaTool")
        WidgetFormulaTool.setWindowModality(QtCore.Qt.ApplicationModal)
        WidgetFormulaTool.resize(500, 525)
        WidgetFormulaTool.setMinimumSize(QtCore.QSize(300, 300))
        WidgetFormulaTool.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Images/asc.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        WidgetFormulaTool.setWindowIcon(icon)
        WidgetFormulaTool.setStyleSheet("QWidget#WidgetFormulaTool {background-color: #FFFFFF}")
        self.gridLayout = QtWidgets.QGridLayout(WidgetFormulaTool)
        self.gridLayout.setContentsMargins(0, 9, 0, 0)
        self.gridLayout.setVerticalSpacing(15)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.search = QtWidgets.QLineEdit(WidgetFormulaTool)
        self.search.setMinimumSize(QtCore.QSize(0, 30))
        self.search.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.search.setFont(font)
        self.search.setStyleSheet("QLineEdit{border: 1px solid #8f8f91; border-right-width: 0px; border-top-left-radius: 5px; border-bottom-left-radius: 5px; padding-left: 5px; }")
        self.search.setObjectName("search")
        self.horizontalLayout.addWidget(self.search)
        self.search_clear = QtWidgets.QPushButton(WidgetFormulaTool)
        self.search_clear.setMinimumSize(QtCore.QSize(40, 30))
        self.search_clear.setMaximumSize(QtCore.QSize(40, 30))
        self.search_clear.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-top-right-radius: 5px ; border-bottom-right-radius: 5px; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #FFFFFF, stop:1 #BAD0E7)}\n"
"QPushButton:hover{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC)}\n"
"QPushButton:pressed{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8)}")
        self.search_clear.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Images/search_clear.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search_clear.setIcon(icon1)
        self.search_clear.setIconSize(QtCore.QSize(20, 20))
        self.search_clear.setObjectName("search_clear")
        self.horizontalLayout.addWidget(self.search_clear)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.table = QtWidgets.QTableView(WidgetFormulaTool)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.table.setFont(font)
        self.table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table.setAlternatingRowColors(True)
        self.table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table.setIconSize(QtCore.QSize(20, 20))
        self.table.setSortingEnabled(True)
        self.table.setWordWrap(False)
        self.table.setObjectName("table")
        self.table.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.table, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(9, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(9, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 1)
        self.fond = QtWidgets.QWidget(WidgetFormulaTool)
        self.fond.setMinimumSize(QtCore.QSize(0, 38))
        self.fond.setMaximumSize(QtCore.QSize(16777215, 38))
        self.fond.setStyleSheet("QWidget#fond{background-color: #DBE4EE}")
        self.fond.setObjectName("fond")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.fond)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(157, 50, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.ok = QtWidgets.QPushButton(self.fond)
        self.ok.setMinimumSize(QtCore.QSize(120, 24))
        self.ok.setMaximumSize(QtCore.QSize(16777215, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.ok.setFont(font)
        self.ok.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-radius: 5px ; padding-right: 10px; padding-left: 10px; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #FFFFFF, stop:1 #BAD0E7); }\n"
"QPushButton:hover{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC); }\n"
"QPushButton:pressed{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8); }")
        self.ok.setShortcut("Ctrl+S")
        self.ok.setObjectName("ok")
        self.horizontalLayout_4.addWidget(self.ok)
        self.quit = QtWidgets.QPushButton(self.fond)
        self.quit.setMinimumSize(QtCore.QSize(120, 24))
        self.quit.setMaximumSize(QtCore.QSize(16777215, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.quit.setFont(font)
        self.quit.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-radius: 5px ; padding-right: 10px; padding-left: 10px; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #FFFFFF, stop:1 #BAD0E7); }\n"
"QPushButton:hover{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC); }\n"
"QPushButton:pressed{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8); }")
        self.quit.setShortcut("Esc")
        self.quit.setObjectName("quit")
        self.horizontalLayout_4.addWidget(self.quit)
        spacerItem3 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.gridLayout.addWidget(self.fond, 2, 0, 1, 3)

        self.retranslateUi(WidgetFormulaTool)
        QtCore.QMetaObject.connectSlotsByName(WidgetFormulaTool)
        WidgetFormulaTool.setTabOrder(self.search, self.search_clear)
        WidgetFormulaTool.setTabOrder(self.search_clear, self.table)

    def retranslateUi(self, WidgetFormulaTool):
        _translate = QtCore.QCoreApplication.translate
        WidgetFormulaTool.setWindowTitle(_translate("WidgetFormulaTool", "Ajout une formule \"Objet\""))
        self.search.setPlaceholderText(_translate("WidgetFormulaTool", "Rechercher"))
        self.search_clear.setToolTip(_translate("WidgetFormulaTool", "Supprimer la recherche"))
        self.ok.setText(_translate("WidgetFormulaTool", "Ajouter"))
        self.quit.setText(_translate("WidgetFormulaTool", "Quitter"))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WidgetFormulaTool = QtWidgets.QWidget()
    ui = Ui_WidgetFormulaTool()
    ui.setupUi(WidgetFormulaTool)
    WidgetFormulaTool.show()
    sys.exit(app.exec_())
