# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Stockage\GIT\GitHub\smartest2\ui\ui_formula_favorite.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormulaFavorite(object):
    def setupUi(self, FormulaFavorite):
        FormulaFavorite.setObjectName("FormulaFavorite")
        FormulaFavorite.setWindowModality(QtCore.Qt.ApplicationModal)
        FormulaFavorite.resize(978, 560)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        FormulaFavorite.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Images/asc.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        FormulaFavorite.setWindowIcon(icon)
        FormulaFavorite.setStyleSheet("QWidget#FormulaFavorite {background-color: #FFFFFF; }")
        self.verticalLayout = QtWidgets.QVBoxLayout(FormulaFavorite)
        self.verticalLayout.setContentsMargins(0, -1, 0, 0)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.onglet = QtWidgets.QTabWidget(FormulaFavorite)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.onglet.setFont(font)
        self.onglet.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.onglet.setObjectName("onglet")
        self.verticalLayout.addWidget(self.onglet)
        self.fond = QtWidgets.QWidget(FormulaFavorite)
        self.fond.setMinimumSize(QtCore.QSize(0, 38))
        self.fond.setMaximumSize(QtCore.QSize(16777215, 38))
        self.fond.setStyleSheet("QWidget#fond{background: #DBE4EE}")
        self.fond.setObjectName("fond")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.fond)
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.bt_enregistrer = QtWidgets.QPushButton(self.fond)
        self.bt_enregistrer.setMinimumSize(QtCore.QSize(120, 24))
        self.bt_enregistrer.setMaximumSize(QtCore.QSize(16777215, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.bt_enregistrer.setFont(font)
        self.bt_enregistrer.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-radius:5px; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #FFFFFF, stop:1 #BAD0E7); }\n"
"QPushButton:hover{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC); }\n"
"QPushButton:pressed{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8); }")
        self.bt_enregistrer.setShortcut("Ctrl+S")
        self.bt_enregistrer.setObjectName("bt_enregistrer")
        self.horizontalLayout.addWidget(self.bt_enregistrer)
        self.bt_quitter = QtWidgets.QPushButton(self.fond)
        self.bt_quitter.setMinimumSize(QtCore.QSize(120, 24))
        self.bt_quitter.setMaximumSize(QtCore.QSize(16777215, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.bt_quitter.setFont(font)
        self.bt_quitter.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-radius:5px ; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #FFFFFF, stop:1 #BAD0E7)}\n"
"QPushButton:hover{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC)}\n"
"QPushButton:pressed{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8)}")
        self.bt_quitter.setShortcut("Esc")
        self.bt_quitter.setObjectName("bt_quitter")
        self.horizontalLayout.addWidget(self.bt_quitter)
        spacerItem1 = QtWidgets.QSpacerItem(6, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.fond)

        self.retranslateUi(FormulaFavorite)
        QtCore.QMetaObject.connectSlotsByName(FormulaFavorite)

    def retranslateUi(self, FormulaFavorite):
        _translate = QtCore.QCoreApplication.translate
        FormulaFavorite.setWindowTitle(_translate("FormulaFavorite", "Gestionnaire de formules"))
        self.bt_enregistrer.setText(_translate("FormulaFavorite", " Enregistrer"))
        self.bt_quitter.setText(_translate("FormulaFavorite", " Annuler"))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormulaFavorite = QtWidgets.QWidget()
    ui = Ui_FormulaFavorite()
    ui.setupUi(FormulaFavorite)
    FormulaFavorite.show()
    sys.exit(app.exec_())
