# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Stockage\GIT\GitHub\smartest2\ui\ui_link_add_again.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LinkAddAgain(object):
    def setupUi(self, LinkAddAgain):
        LinkAddAgain.setObjectName("LinkAddAgain")
        LinkAddAgain.resize(250, 350)
        LinkAddAgain.setWindowTitle("Form")
        LinkAddAgain.setStyleSheet("QWidget#LinkAddAgain {background:rgb(248, 248, 248)}")
        self.verticalLayout = QtWidgets.QVBoxLayout(LinkAddAgain)
        self.verticalLayout.setContentsMargins(-1, 6, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.search_bar = QtWidgets.QLineEdit(LinkAddAgain)
        self.search_bar.setMinimumSize(QtCore.QSize(0, 30))
        self.search_bar.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.search_bar.setFont(font)
        self.search_bar.setStyleSheet("QLineEdit{border: 1px solid #8f8f91; border-right-width: 0px; border-top-left-radius: 5px; border-bottom-left-radius: 5px; padding-left: 5px; }")
        self.search_bar.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.search_bar.setObjectName("search_bar")
        self.horizontalLayout.addWidget(self.search_bar)
        self.search_clear = QtWidgets.QPushButton(LinkAddAgain)
        self.search_clear.setMinimumSize(QtCore.QSize(40, 30))
        self.search_clear.setMaximumSize(QtCore.QSize(40, 30))
        self.search_clear.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-top-right-radius: 5px ; border-bottom-right-radius: 5px; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #FFFFFF, stop:1 #BAD0E7)}\n"
"QPushButton:hover{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC)}\n"
"QPushButton:pressed{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8)}")
        self.search_clear.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Images/search_clear.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search_clear.setIcon(icon)
        self.search_clear.setIconSize(QtCore.QSize(20, 20))
        self.search_clear.setObjectName("search_clear")
        self.horizontalLayout.addWidget(self.search_clear)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.links_list = QtWidgets.QListView(LinkAddAgain)
        self.links_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.links_list.setAlternatingRowColors(True)
        self.links_list.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.links_list.setIconSize(QtCore.QSize(24, 24))
        self.links_list.setObjectName("links_list")
        self.verticalLayout.addWidget(self.links_list)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ok = QtWidgets.QPushButton(LinkAddAgain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ok.sizePolicy().hasHeightForWidth())
        self.ok.setSizePolicy(sizePolicy)
        self.ok.setMinimumSize(QtCore.QSize(100, 0))
        self.ok.setMaximumSize(QtCore.QSize(16777215, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.ok.setFont(font)
        self.ok.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-radius: 5px ; padding-right: 10px; padding-left: 10px; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #FFFFFF, stop:1 #BAD0E7); }\n"
"QPushButton:hover{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC); }\n"
"QPushButton:pressed{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8); }")
        self.ok.setObjectName("ok")
        self.horizontalLayout_3.addWidget(self.ok)
        self.quit = QtWidgets.QPushButton(LinkAddAgain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quit.sizePolicy().hasHeightForWidth())
        self.quit.setSizePolicy(sizePolicy)
        self.quit.setMinimumSize(QtCore.QSize(100, 24))
        self.quit.setMaximumSize(QtCore.QSize(16777215, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.quit.setFont(font)
        self.quit.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-radius: 5px ; padding-right: 10px; padding-left: 10px; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #FFFFFF, stop:1 #BAD0E7); }\n"
"QPushButton:hover{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC); }\n"
"QPushButton:pressed{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8); }")
        self.quit.setObjectName("quit")
        self.horizontalLayout_3.addWidget(self.quit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(LinkAddAgain)
        QtCore.QMetaObject.connectSlotsByName(LinkAddAgain)

    def retranslateUi(self, LinkAddAgain):
        _translate = QtCore.QCoreApplication.translate
        self.search_bar.setPlaceholderText(_translate("LinkAddAgain", "Rechercher"))
        self.search_clear.setToolTip(_translate("LinkAddAgain", "Supprimer la recherche"))
        self.ok.setText(_translate("LinkAddAgain", "Ajouter"))
        self.quit.setText(_translate("LinkAddAgain", "Annuler"))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LinkAddAgain = QtWidgets.QWidget()
    ui = Ui_LinkAddAgain()
    ui.setupUi(LinkAddAgain)
    LinkAddAgain.show()
    sys.exit(app.exec_())
