# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Stockage\GIT\GitHub\smartest2\ui\ui_message_existing.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MessageExisting(object):
    def setupUi(self, MessageExisting):
        MessageExisting.setObjectName("MessageExisting")
        MessageExisting.resize(568, 229)
        MessageExisting.setWindowTitle("Allplan - SmartCatalog")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Images/search_replace.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MessageExisting.setWindowIcon(icon)
        MessageExisting.setStyleSheet("QWidget#MessageExisting{background-color: #FFFFFF; }")
        self.gridLayout = QtWidgets.QGridLayout(MessageExisting)
        self.gridLayout.setContentsMargins(0, -1, 0, 0)
        self.gridLayout.setVerticalSpacing(15)
        self.gridLayout.setObjectName("gridLayout")
        self.fond = QtWidgets.QWidget(MessageExisting)
        self.fond.setMinimumSize(QtCore.QSize(0, 38))
        self.fond.setMaximumSize(QtCore.QSize(16777215, 38))
        self.fond.setStyleSheet("QWidget#fond{background: #DBE4EE}")
        self.fond.setObjectName("fond")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.fond)
        self.horizontalLayout_3.setContentsMargins(6, 0, 6, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(6, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.update = QtWidgets.QPushButton(self.fond)
        self.update.setMinimumSize(QtCore.QSize(0, 24))
        self.update.setMaximumSize(QtCore.QSize(16777215, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.update.setFont(font)
        self.update.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-radius: 5px ; padding-right: 10px; padding-left: 10px; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #FFFFFF, stop:1 #BAD0E7); }\n"
"QPushButton:hover{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC); }\n"
"QPushButton:pressed{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8); }")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Images/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.update.setIcon(icon1)
        self.update.setIconSize(QtCore.QSize(18, 18))
        self.update.setObjectName("update")
        self.horizontalLayout_3.addWidget(self.update)
        self.replace = QtWidgets.QPushButton(self.fond)
        self.replace.setMinimumSize(QtCore.QSize(0, 24))
        self.replace.setMaximumSize(QtCore.QSize(16777215, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.replace.setFont(font)
        self.replace.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-radius: 5px ; padding-right: 10px; padding-left: 10px; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #FFFFFF, stop:1 #BAD0E7); }\n"
"QPushButton:hover{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC); }\n"
"QPushButton:pressed{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8); }")
        self.replace.setIcon(icon)
        self.replace.setIconSize(QtCore.QSize(18, 18))
        self.replace.setObjectName("replace")
        self.horizontalLayout_3.addWidget(self.replace)
        self.duplicate = QtWidgets.QPushButton(self.fond)
        self.duplicate.setMinimumSize(QtCore.QSize(0, 24))
        self.duplicate.setMaximumSize(QtCore.QSize(16777215, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.duplicate.setFont(font)
        self.duplicate.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-radius: 5px ; padding-right: 10px; padding-left: 10px; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #FFFFFF, stop:1 #BAD0E7); }\n"
"QPushButton:hover{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC); }\n"
"QPushButton:pressed{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8); }")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Images/folder_paste.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.duplicate.setIcon(icon2)
        self.duplicate.setIconSize(QtCore.QSize(18, 18))
        self.duplicate.setObjectName("duplicate")
        self.horizontalLayout_3.addWidget(self.duplicate)
        self.quit = QtWidgets.QPushButton(self.fond)
        self.quit.setMinimumSize(QtCore.QSize(0, 24))
        self.quit.setMaximumSize(QtCore.QSize(16777215, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.quit.setFont(font)
        self.quit.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-radius: 5px ; padding-right: 10px; padding-left: 10px; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #FFFFFF, stop:1 #BAD0E7); }\n"
"QPushButton:hover{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC); }\n"
"QPushButton:pressed{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8); }")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Images/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.quit.setIcon(icon3)
        self.quit.setIconSize(QtCore.QSize(18, 18))
        self.quit.setObjectName("quit")
        self.horizontalLayout_3.addWidget(self.quit)
        spacerItem1 = QtWidgets.QSpacerItem(6, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.gridLayout.addWidget(self.fond, 2, 0, 1, 4)
        spacerItem2 = QtWidgets.QSpacerItem(9, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 3, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(9)
        self.verticalLayout.setObjectName("verticalLayout")
        self.message = QtWidgets.QLabel(MessageExisting)
        self.message.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.message.setFont(font)
        self.message.setText("")
        self.message.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.message.setObjectName("message")
        self.verticalLayout.addWidget(self.message)
        self.details = QtWidgets.QTextBrowser(MessageExisting)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.details.setFont(font)
        self.details.setStyleSheet("QTextBrowser{border: 1px solid #8f8f91; padding-left: 5px; }")
        self.details.setObjectName("details")
        self.verticalLayout.addWidget(self.details)
        self.chk_all = QtWidgets.QCheckBox(MessageExisting)
        self.chk_all.setMinimumSize(QtCore.QSize(0, 24))
        self.chk_all.setMaximumSize(QtCore.QSize(16777215, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.chk_all.setFont(font)
        self.chk_all.setText("")
        self.chk_all.setChecked(True)
        self.chk_all.setObjectName("chk_all")
        self.verticalLayout.addWidget(self.chk_all)
        self.gridLayout.addLayout(self.verticalLayout, 0, 2, 2, 1)
        spacerItem3 = QtWidgets.QSpacerItem(9, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 0, 1, 1)

        self.retranslateUi(MessageExisting)
        QtCore.QMetaObject.connectSlotsByName(MessageExisting)
        MessageExisting.setTabOrder(self.quit, self.duplicate)
        MessageExisting.setTabOrder(self.duplicate, self.replace)
        MessageExisting.setTabOrder(self.replace, self.update)
        MessageExisting.setTabOrder(self.update, self.chk_all)
        MessageExisting.setTabOrder(self.chk_all, self.details)

    def retranslateUi(self, MessageExisting):
        pass
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MessageExisting = QtWidgets.QWidget()
    ui = Ui_MessageExisting()
    ui.setupUi(MessageExisting)
    MessageExisting.show()
    sys.exit(app.exec_())
