# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Stockage\GIT\GitHub\smartest2\ui\ui_message_children.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MessageChildren(object):
    def setupUi(self, MessageChildren):
        MessageChildren.setObjectName("MessageChildren")
        MessageChildren.resize(570, 227)
        MessageChildren.setWindowTitle("Allplan - SmartCatalog")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Images/hierarchy_add_child.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MessageChildren.setWindowIcon(icon)
        MessageChildren.setStyleSheet("QWidget#MessageChildren{background-color: #FFFFFF; }")
        self.gridLayout = QtWidgets.QGridLayout(MessageChildren)
        self.gridLayout.setContentsMargins(0, -1, 0, 0)
        self.gridLayout.setVerticalSpacing(15)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(9, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.fond = QtWidgets.QWidget(MessageChildren)
        self.fond.setMinimumSize(QtCore.QSize(0, 38))
        self.fond.setMaximumSize(QtCore.QSize(16777215, 38))
        self.fond.setStyleSheet("QWidget#fond{background: #DBE4EE}")
        self.fond.setObjectName("fond")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.fond)
        self.horizontalLayout_3.setContentsMargins(6, 0, 6, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(6, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.ok = QtWidgets.QPushButton(self.fond)
        self.ok.setMinimumSize(QtCore.QSize(0, 24))
        self.ok.setMaximumSize(QtCore.QSize(16777215, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.ok.setFont(font)
        self.ok.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-radius: 5px ; padding-right: 10px; padding-left: 10px; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #FFFFFF, stop:1 #BAD0E7); }\n"
"QPushButton:hover{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC); }\n"
"QPushButton:pressed{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8); }")
        self.ok.setText("")
        self.ok.setIconSize(QtCore.QSize(18, 18))
        self.ok.setObjectName("ok")
        self.horizontalLayout_3.addWidget(self.ok)
        self.no = QtWidgets.QPushButton(self.fond)
        self.no.setMinimumSize(QtCore.QSize(0, 24))
        self.no.setMaximumSize(QtCore.QSize(16777215, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.no.setFont(font)
        self.no.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-radius: 5px ; padding-right: 10px; padding-left: 10px; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #FFFFFF, stop:1 #BAD0E7); }\n"
"QPushButton:hover{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC); }\n"
"QPushButton:pressed{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8); }")
        self.no.setText("")
        self.no.setIconSize(QtCore.QSize(18, 18))
        self.no.setObjectName("no")
        self.horizontalLayout_3.addWidget(self.no)
        self.quit = QtWidgets.QPushButton(self.fond)
        self.quit.setMinimumSize(QtCore.QSize(0, 24))
        self.quit.setMaximumSize(QtCore.QSize(16777215, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.quit.setFont(font)
        self.quit.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-radius: 5px ; padding-right: 10px; padding-left: 10px; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #FFFFFF, stop:1 #BAD0E7); }\n"
"QPushButton:hover{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC); }\n"
"QPushButton:pressed{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8); }")
        self.quit.setIconSize(QtCore.QSize(18, 18))
        self.quit.setObjectName("quit")
        self.horizontalLayout_3.addWidget(self.quit)
        spacerItem2 = QtWidgets.QSpacerItem(6, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.gridLayout.addWidget(self.fond, 2, 0, 1, 3)
        spacerItem3 = QtWidgets.QSpacerItem(9, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 2, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(9)
        self.verticalLayout.setObjectName("verticalLayout")
        self.message = QtWidgets.QLabel(MessageChildren)
        self.message.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.message.setFont(font)
        self.message.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.message.setObjectName("message")
        self.verticalLayout.addWidget(self.message)
        self.details = QtWidgets.QTextBrowser(MessageChildren)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.details.setFont(font)
        self.details.setStyleSheet("QTextBrowser{border: 1px solid #8f8f91; padding-left: 5px; }")
        self.details.setObjectName("details")
        self.verticalLayout.addWidget(self.details)
        self.chk_all = QtWidgets.QCheckBox(MessageChildren)
        self.chk_all.setMinimumSize(QtCore.QSize(0, 24))
        self.chk_all.setMaximumSize(QtCore.QSize(16777215, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.chk_all.setFont(font)
        self.chk_all.setChecked(True)
        self.chk_all.setObjectName("chk_all")
        self.verticalLayout.addWidget(self.chk_all)
        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 2, 1)

        self.retranslateUi(MessageChildren)
        QtCore.QMetaObject.connectSlotsByName(MessageChildren)
        MessageChildren.setTabOrder(self.quit, self.no)
        MessageChildren.setTabOrder(self.no, self.ok)
        MessageChildren.setTabOrder(self.ok, self.chk_all)
        MessageChildren.setTabOrder(self.chk_all, self.details)

    def retranslateUi(self, MessageChildren):
        _translate = QtCore.QCoreApplication.translate
        self.quit.setText(_translate("MessageChildren", "Annuler"))
        self.chk_all.setText(_translate("MessageChildren", "Appliquer aux éléments suivants"))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MessageChildren = QtWidgets.QWidget()
    ui = Ui_MessageChildren()
    ui.setupUi(MessageChildren)
    MessageChildren.show()
    sys.exit(app.exec_())
