# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Stockage\GIT\GitHub\smartest2\ui\ui_trade.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Trade(object):
    def setupUi(self, Trade):
        Trade.setObjectName("Trade")
        Trade.setWindowModality(QtCore.Qt.ApplicationModal)
        Trade.resize(563, 430)
        Trade.setMinimumSize(QtCore.QSize(300, 300))
        Trade.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Images/asc.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Trade.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(Trade)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.search = QtWidgets.QLineEdit(Trade)
        self.search.setMinimumSize(QtCore.QSize(0, 30))
        self.search.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.search.setFont(font)
        self.search.setStyleSheet("QLineEdit{border: 1px solid #8f8f91; border-right-width: 0px; border-top-left-radius: 5px; border-bottom-left-radius: 5px; padding-left: 5px; }")
        self.search.setObjectName("search")
        self.horizontalLayout.addWidget(self.search)
        self.search_clear = QtWidgets.QPushButton(Trade)
        self.search_clear.setMinimumSize(QtCore.QSize(30, 30))
        self.search_clear.setMaximumSize(QtCore.QSize(30, 30))
        self.search_clear.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-top-right-radius: 5px ; border-bottom-right-radius: 5px; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #FFFFFF, stop:1 #BAD0E7)}\n"
"QPushButton:hover{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC)}\n"
"QPushButton:pressed{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8)}")
        self.search_clear.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Images/search_clear.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search_clear.setIcon(icon1)
        self.search_clear.setIconSize(QtCore.QSize(20, 20))
        self.search_clear.setObjectName("search_clear")
        self.horizontalLayout.addWidget(self.search_clear)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.table = QtWidgets.QTableView(Trade)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.table.setFont(font)
        self.table.setStyleSheet("QHeaderView {background-color: #d8e9e8}")
        self.table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table.setAlternatingRowColors(True)
        self.table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table.setSortingEnabled(True)
        self.table.setObjectName("table")
        self.table.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.table)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.ok = QtWidgets.QPushButton(Trade)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ok.sizePolicy().hasHeightForWidth())
        self.ok.setSizePolicy(sizePolicy)
        self.ok.setMinimumSize(QtCore.QSize(100, 0))
        self.ok.setMaximumSize(QtCore.QSize(16777215, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.ok.setFont(font)
        self.ok.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-radius:5px ; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #FFFFFF, stop:1 #BAD0E7)}\n"
"QPushButton:hover{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC)}\n"
"QPushButton:pressed{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8)}")
        self.ok.setObjectName("ok")
        self.horizontalLayout_3.addWidget(self.ok)
        self.quit = QtWidgets.QPushButton(Trade)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quit.sizePolicy().hasHeightForWidth())
        self.quit.setSizePolicy(sizePolicy)
        self.quit.setMinimumSize(QtCore.QSize(100, 24))
        self.quit.setMaximumSize(QtCore.QSize(16777215, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.quit.setFont(font)
        self.quit.setStyleSheet("QPushButton{border: 1px solid #8f8f91; border-radius:5px ; background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #FFFFFF, stop:1 #BAD0E7)}\n"
"QPushButton:hover{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #F8F8F8, stop:1 #8FADCC)}\n"
"QPushButton:pressed{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #8FADCC, stop:1 #F8F8F8)}")
        self.quit.setObjectName("quit")
        self.horizontalLayout_3.addWidget(self.quit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Trade)
        QtCore.QMetaObject.connectSlotsByName(Trade)

    def retranslateUi(self, Trade):
        _translate = QtCore.QCoreApplication.translate
        Trade.setWindowTitle(_translate("Trade", "Ajout une formule \"Métier\""))
        self.search.setPlaceholderText(_translate("Trade", "Rechercher"))
        self.search_clear.setToolTip(_translate("Trade", "Supprimer la recherche"))
        self.ok.setText(_translate("Trade", "Valider"))
        self.quit.setText(_translate("Trade", "Annuler"))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Trade = QtWidgets.QWidget()
    ui = Ui_Trade()
    ui.setupUi(Trade)
    Trade.show()
    sys.exit(app.exec_())
